# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c62452b126127d4be23d3e7af7bac27fa043595a9f387a86519d6d3b8f8161b70d8a2b1687111709a9f5601ded1860d611e3cd1689368cd865c555b4feeaa1

test:
  secret_key_base: daced1a33afcfed50e71f00838a4d2035c4e03e59b4c863dc77ac17a46c85cc9dd13907ce58175a066fa9e51d0a368f1ed050e8deea99986217062c03faeed93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
